/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamedica;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author super
 */
public class CancelarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form CancelarConsulta
     */
    public CancelarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxHorario = new javax.swing.JComboBox<>();
        nMedicoTxt = new javax.swing.JTextField();
        nPacienteTxt = new javax.swing.JTextField();
        dataTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CANCELAMENTO DE CONSULTAS");
        setMaximumSize(new java.awt.Dimension(717, 508));
        setMinimumSize(new java.awt.Dimension(717, 508));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("CANCELAMENTO DE CONSULTAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 264, 57);

        jLabel2.setText("Nome Medico:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 130, 16);

        jLabel3.setText("Nome Paciente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 240, 83, 16);

        jLabel4.setText("Data Consulta(formato dd/mm/aaaa):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 202, 16);

        jLabel5.setText("Horario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 340, 118, 16);

        boxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00h", "9:00h", "10:00h", "11:00h" }));
        getContentPane().add(boxHorario);
        boxHorario.setBounds(140, 340, 117, 22);
        getContentPane().add(nMedicoTxt);
        nMedicoTxt.setBounds(180, 190, 245, 22);
        getContentPane().add(nPacienteTxt);
        nPacienteTxt.setBounds(180, 240, 204, 22);
        getContentPane().add(dataTxt);
        dataTxt.setBounds(320, 290, 93, 22);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 410, 72, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 410, 76, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/blackkk.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -20, 980, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PosLogin frame = new PosLogin();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json="";
        try {
            json = String.join(" ",Files.readAllLines(Paths.get("pacientes.json"),StandardCharsets.UTF_8));
        } catch (IOException ex) {
            Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        String json2="";
        try {
            json2 = String.join(" ",Files.readAllLines(Paths.get("medicos.json"),StandardCharsets.UTF_8));
        } catch (IOException ex) {
            Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.lang.reflect.Type listTypePaciente = new TypeToken <ArrayList<Paciente>>(){}.getType();
        ArrayList<Paciente> pacientes = gson.fromJson(json,listTypePaciente);
        java.lang.reflect.Type listTypeMedico = new TypeToken <ArrayList<Medico>>(){}.getType();
        ArrayList<Medico> medicos = gson.fromJson(json2, listTypeMedico);
        String data = dataTxt.getText();
        String[] vetorData = data.split("(?!^)");
        boolean verificador = false;
        if(vetorData.length!=10){
            JOptionPane.showMessageDialog(null, "Olá, data inserida inválida.");
        }
        int index=0;
        int index2=0;
        boolean verificador1 = false;
        boolean verificador2= false;
        for(int z=0;z<medicos.size();z++){
            Medico medico = medicos.get(z);
            ArrayList<Consulta> consultas = medico.getConsultas();
            for (int i =0;i<consultas.size();i++){
                Consulta consulta = consultas.get(i);
                if(consulta.getNomeMedico().equals(nMedicoTxt.getText().toUpperCase())&&consulta.getNomePaciente().equals(nPacienteTxt.getText().toUpperCase())&&consulta.getData().equals(dataTxt.getText())&&consulta.getHorario().equals(boxHorario.getSelectedItem())){
                    medicos.remove(index);
                    verificador=true;
                    medico.cancelarAgendamento(consulta);
                    
                    try {
                        json = String.join(" ",Files.readAllLines(Paths.get("usuario.json"),StandardCharsets.UTF_8));
                        Medico medicoLogin = gson.fromJson(json, Medico.class);
                        ArrayList<Consulta> teste = medicoLogin.gerarRelatorio("02/02/2005","02/02/2007");
                        Writer writer = new FileWriter("usuario.json");
                        gson.toJson(medico,writer);
                        writer.flush();
                        writer.close();
                    } catch (ExeptionNoMedico ex) {
                        System.out.println(ex.toString());
                        
                    }
                    catch (IOException | ParseException ex) {
                        Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                    } catch(Exception e){
                        System.out.println(e);
                    }
                    medicos.add(medico);
                    verificador1=true;
                }
            }
            index=index+1;
        }
        if(verificador==false){
                JOptionPane.showMessageDialog(null, "Olá, médico, paciente, data, ou horario não encontrados, por favor, gere um relatorio.");
            }
        try (Writer writer = new FileWriter("medicos.json")) {
                        String jsonNovo = gson.toJson(medicos);
                        gson.toJson(medicos,writer);
                        writer.flush();
                        writer.close();
                    } catch (IOException ex) {
                        Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                    }
        for(int x =0;x<pacientes.size();x++){
            Paciente paciente = pacientes.get(x);
            ArrayList<Consulta> consultas = paciente.getConsultas();
            for (int i = 0;i<consultas.size();i++){
                Consulta consulta = consultas.get(i);
                if(consulta.getNomeMedico().equals(nMedicoTxt.getText().toUpperCase())&&consulta.getNomePaciente().equals(nPacienteTxt.getText().toUpperCase())&&consulta.getData().equals(dataTxt.getText())&&consulta.getHorario().equals(boxHorario.getSelectedItem())){
                    pacientes.remove(index2);
                    paciente.cancelarAgendamento(consulta);
                    
                    for(int z =0;z<pacientes.size();z++){
                        Paciente newPaciente = pacientes.get(z);
                        newPaciente.verificarListas(consulta);
                    }
                    try {
                        json = String.join(" ",Files.readAllLines(Paths.get("usuario.json"),StandardCharsets.UTF_8));
                        Paciente pacienteLogin = gson.fromJson(json, Paciente.class);
                        ArrayList<Consulta> teste = pacienteLogin.gerarRelatorio("02/02/2005","02/02/2007");
                        Writer writer = new FileWriter("usuario.json");
                        gson.toJson(paciente,writer);
                        writer.flush();
                        writer.close();
                    } catch (ExceptionNoPaciente ex) {
                        
                        System.out.println(ex.toString());
                    }
                    catch (IOException ex) {
                        Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    catch (ParseException ex) {
                        Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pacientes.add(paciente);
                    verificador2=true;
                    break;
                }
            }
            index2 = index2+1;
        }
        try (Writer writer = new FileWriter("pacientes.json")) {
                        String jsonNovo = gson.toJson(pacientes);
                        gson.toJson(pacientes,writer);
                        writer.flush();
                        writer.close();
                    } catch (IOException ex) {
                        Logger.getLogger(CancelarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                    }
        if(verificador1==true&&verificador2==true){
            JOptionPane.showMessageDialog(null, "Olá, o cancelamento deu certo!"); 
            PosLogin frame = new PosLogin();
        frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxHorario;
    private javax.swing.JTextField dataTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nMedicoTxt;
    private javax.swing.JTextField nPacienteTxt;
    // End of variables declaration//GEN-END:variables
}
