package com.mycompany.agendamedica;

import javax.swing.JOptionPane;
import model.dao.MedicoDAO;
import model.dao.PacienteDAO;
/**
 *
 * @author super
 */
public class EditarUsuario extends javax.swing.JFrame {

    private MedicoDAO medicoDAO;
    private PacienteDAO pacienteDAO;

    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
        medicoDAO = new MedicoDAO();
        pacienteDAO = new PacienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        // ... Código gerado pelo Editor de Formulários do NetBeans ...
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        PosLogin frame = new PosLogin();
        frame.setVisible(true);
        this.dispose();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String nome = nomeTxt.getText().toUpperCase();
            String senha = senhaTxt.getText();
            boolean verificador = false;

            // Caso login médico
//            if (chxMedico.isSelected() && !chxPaciente.isSelected()) {
//                Medico medico = medicoDAO.buscarPorNomeESenha(nome, senha);
//                if (medico != null) {
//                    verificador = true;
//                    if (jcbMedico.getModel().getSelectedItem().equals("Especialidade")) {
//                        medico.setEspecialidade(eTxt.getText());
//                    } else if (jcbMedico.getModel().getSelectedItem().equals("Nome")) {
//                        medico.setNome(nTxt.getText().toUpperCase());
//                    } else if (jcbMedico.getModel().getSelectedItem().equals("Senha")) {
//                        medico.setSenha(sTxt.getText());
//                    }
//                    medicoDAO.atualizarMedico(medico);
//                    JOptionPane.showMessageDialog(null, "Olá, a edição deu certo!");
//                    this.dispose();
//                }
//            }

            // Caso login paciente
//            if (!chxMedico.isSelected() && chxPaciente.isSelected()) {
//                Paciente paciente = pacienteDAO.buscarPorNomeESenha(nome, senha);
//                if (paciente != null) {
//                    verificador = true;
//                    if (jcbPaciente.getModel().getSelectedItem().equals("Idade")) {
//                        paciente.setIdade(iTxt.getText());
//                    } else if (jcbPaciente.getModel().getSelectedItem().equals("Nome")) {
//                        paciente.setNome(nTxt.getText().toUpperCase());
//                    } else if (jcbPaciente.getModel().getSelectedItem().equals("Senha")) {
//                        paciente.setSenha(sTxt.getText());
//                    }
//                    pacienteDAO.atualizarPaciente(paciente);
//                    JOptionPane.showMessageDialog(null, "Olá, a edição deu certo!");
//                    this.dispose();
//                }
//            }

            // Caso erro
            if (!verificador) {
                JOptionPane.showMessageDialog(null, "Não foi possível editar, cheque se o nome e senha estão corretos.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar editar o usuário: " + ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        // Inicialização dos componentes de interface gráfica
    }

    private void chxMedicoActionPerformed(java.awt.event.ActionEvent evt) {
        // Configura a visibilidade dos componentes baseados no tipo de usuário selecionado
    }

    private void chxPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        // Configura a visibilidade dos componentes baseados no tipo de usuário selecionado
    }

    private void jcbMedicoActionPerformed(java.awt.event.ActionEvent evt) {
        // Configura a visibilidade dos campos baseados na opção selecionada no ComboBox
    }

    private void jcbPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        // Configura a visibilidade dos campos baseados na opção selecionada no ComboBox
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox chxMedico;
    private javax.swing.JCheckBox chxPaciente;
    private javax.swing.JTextField eTxt;
    private javax.swing.JTextField iTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcbMedico;
    private javax.swing.JComboBox<String> jcbPaciente;
    private javax.swing.JLabel lblEspecialidadeNova;
    private javax.swing.JLabel lblIdadeNova;
    private javax.swing.JLabel lblNomeNovo;
    private javax.swing.JLabel lblSenhaNova;
    private javax.swing.JTextField nTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JTextField sTxt;
    private javax.swing.JTextField senhaTxt;
    // End of variables declaration                   
}